### ISSUE TITLE
tox errors with the python in docs

### ISSUE THREAD

**Issue by rikvl** [mhvk/screens#21]
Currently, running `tox -e test` gives errors when there is a build of the documentation. The problem is the
`from example_figure import simple_figure`
statements in `docs/examples/simple_examples.rst` which import from a local file. Here's an example of the error messages I get:

<pre>
__________________ ERROR collecting docs/_build/html/examples/simple_examples-1.py ___________________
../../docs/_build/html/examples/simple_examples-1.py:3: in <module>
    from example_figure import simple_figure
E   ModuleNotFoundError: No module named 'example_figure'
</pre>

I'm unsure how to fix this.
- Either include something like `--exclude-dir=docs/_build` somewhere in `tox.ini` (where/how exactly?)
- or change how the python part of the documentation is set up.

For now, a workaround is to remove `docs/_build` before running `tox -e test`.

**Comment by mhvk** [comment]
Maybe just `from .example_figure import simple_figure`?  Alternatively, for now in the .rst file, just do `.. doctest-skip-all`.

**Comment by rikvl** [comment]
Neither of the two solutions you proposed worked, but I think I found a solution.

The problem was that pytest went into `docs/_build/html/examples` and started running all the little bits of python code created by the `.. plot::` directives in the .rst files. I think these are created so someone browsing the documentation can in principle view the code that generated a particular figure (though we switched off that option using `plot_html_show_source_link = False` in `docs/conf.py`) -- I didn't find a way to avoid generating these .py files in the build.

I tried including the modules that couldn't be found in the .rst file (so they would also be copied to `docs/_build/html/examples` during the build) with
<pre>
.. plot:: ./examples/hue_cycle_cmap.py

.. plot:: ./examples/example_figure.py
    :nofigs:
</pre>
That made some sense to me because it would allow someone browsing the docs to find all the code needed to generate the figures (if we hadn't switched off the source viewing option). It made the original pytest errors disappear, but there were new errors like this:
<pre>
__________________________ ERROR collecting docs/examples/example_figure.py __________________________
../../.tox/test/lib/python3.9/site-packages/pytest_doctestplus/plugin.py:206: in collect
    module = self.fspath.pyimport()
../../.tox/test/lib/python3.9/site-packages/py/_path/local.py:724: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('example_figure', '/Users/rik/cita/screens/docs/_build/html/examples/example_figure.py', local('/Users/rik/cita/screens/docs/examples/example_figure.py'))
</pre>
In addition, running `tox -e test` now started generating the figures, making them pop up one by one while doing the tests... :/

The solution I found was to tell pytest not to look in `docs/_build` by setting the option `norecursedirs = _build` in `setup.cfg` (see PR #22). The [pytest documentation](https://docs.pytest.org/en/stable/example/pythoncollection.html#changing-directory-recursion) specifically mentions using this to "tell pytest to not recurse into typical ... sphinx-build directories".

Can you check if this is alright and merge the PR if you agree?
