### ISSUE TITLE
Possibly wrong sign in dynspec.jacobian

### ISSUE THREAD

**Issue by rikvl** [mhvk/screens#24]
Given the fix in the phasor function (#16), maybe this minus sign shouldn't be there.

https://github.com/mhvk/screens/blob/5b5c232f4265622d9683ec5795e221708e429a58/screens/dynspec.py#L314

That may also have consequences (sign changes) in the code in this ``jacobian`` method.

**Comment by mhvk** [comment]
Yes, looks like that sign change needs to be propagated. Nice catch!
