### ISSUE TITLE
Potential Small Bug With Distance Units in two_screens.py

### ISSUE THREAD

**Issue by IMFardz** [mhvk/screens#47]
It seems that the 3d modelling in two_screens.py does not work when I change the units of the pulsar and screen distances. For instance, if I add the following lines of code to the beginning of two_screens.py, I find that the 3d diagram looks different, but the dynamic and secondary spectrum look the same. 

`dp = 0.75*u.kpc

d2 = 0.50*u.kpc

d1 = 0.25*u.kpc

dp = dp.to_value(u.pc) * u.pc

d2 = d2.to_value(u.pc) * u.pc

d1 = d1.to_value(u.pc) * u.pc`

**Comment by mhvk** [comment]
Thanks! Given that the dynamic spectrum looks the same, most likely, it is the plotting that is wrong (matplotlib only partially deals with units). I'll try to find out where the problem lies.

**Comment by mhvk** [comment]
OK, fix in #48. Thanks again for reporting!
